
 
####
GET http://localhost:8080/health/ HTTP/1.1
 

### 

## Scrape Auxiliadora Predial Listing
POST http://localhost:8080/scrape HTTP/1.1
content-type: application/json

{
"URLs": ["https://www.auxiliadorapredial.com.br/imovel/venda/479119/casa+Imbituba+Santa+Catarina"],
"selectors": {
"content": [
"section.section-sobre-detalhe #descricao div.half-text-hidden",
"section.section-sobre-detalhe #descricao",
"[class*=\"descricao\"]",
"[class*=\"description\"]",
],
"photos": [
"dialog.mosaico-container li.item-mosaico img",
"[class*=\"mosaico\"] img",
"[class*=\"gallery\"] img",
"img[src*=\"imovel\"]",
],
}